# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-05 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthoerModel',
            new_name='AuthorModel',
        ),
    ]
