# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20190505_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authormodel',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True, verbose_name='电子邮箱'),
        ),
    ]
