# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseblog',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.AuthorProfile', to_field='username'),
        ),
        migrations.AddField(
            model_name='baseblog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.BlogCategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='baseblog',
            name='tags',
            field=models.ManyToManyField(to='base.Tags', verbose_name='标签'),
        ),
    ]
