# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-30 06:48
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32, verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类列表',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/articlepicture', verbose_name='头像')),
                ('comment_enable', models.BooleanField(choices=[(True, '开启评论'), (False, '关闭评论')], default=True, verbose_name='是否开启评论功能')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('like', models.IntegerField(default=0, verbose_name='点赞')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='文章内容')),
                ('brief_introduction', models.TextField(blank=True, max_length=128, null=True, verbose_name='文章简介')),
                ('istop', models.BooleanField(choices=[(True, '置顶'), (False, '不置顶')], default=False, verbose_name='置顶')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章列表',
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=32, verbose_name='书籍分类')),
            ],
            options={
                'verbose_name': '书籍分类',
                'verbose_name_plural': '书籍分类列表',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=20, verbose_name='评论者昵称')),
                ('content', models.CharField(blank=True, max_length=250, null=True, verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('like', models.IntegerField(default=0, verbose_name='评论点赞')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='article.ArticleModel')),
            ],
            options={
                'verbose_name': '文章评论',
                'verbose_name_plural': '文章评论列表',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=32, verbose_name='标签名称')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='标签描述')),
                ('color', models.CharField(choices=[('#878D99', '灰色'), ('#409EFF', '蓝色'), ('#67C23A', '绿色'), ('#EB9E05', '黄色'), ('#FA5555', '红色')], default='#409EFF', max_length=20, verbose_name='标签颜色')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签列表',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名字')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号码')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='邮箱')),
                ('gender', models.CharField(blank=True, choices=[('0', 'female'), ('1', 'male')], max_length=2, null=True, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='头像')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息列表',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.User', to_field='name'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='article.ArticleCategory', verbose_name='文章分类'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tags',
            field=models.ManyToManyField(to='article.Tags', verbose_name='标签'),
        ),
    ]
