# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 07:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='belong_root',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='super_comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
