# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-16 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='comment_enable',
            field=models.BooleanField(choices=[(True, '开启评论'), (False, '关闭评论')], default=True, verbose_name='是否开启评论功能'),
        ),
    ]
