# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-16 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_articlemodel_comment_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='catgory',
            new_name='category',
        ),
    ]
