# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190516_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '文章评论', 'verbose_name_plural': '文章评论列表'},
        ),
        migrations.RenameField(
            model_name='catgory',
            old_name='category',
            new_name='catgory',
        ),
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(choices=[('#878D99', '灰色'), ('#409EFF', '蓝色'), ('#67C23A', '绿色'), ('#EB9E05', '黄色'), ('#FA5555', '红色')], default='#409EFF', max_length=20, verbose_name='标签颜色'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/articlepicture', verbose_name='头像'),
        ),
    ]
